include:
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'

stages:
  - deploy

deploy-job:
  stage: deploy
  image: alpine/k8s:1.22.6
  rules:
    - changes:
      - kubernetes/**/*
  script:
    - mkdir ~/.kube/
    - chmod 700 ~/.kube/
    - echo "$KUBE_CONFIG" > ~/.kube/config
    - chmod 644 ~/.kube/config
    - cat /root/.kube/config
    - cd ~/.kube
    - ls -a
    - pwd
    - kubectl get pods 
    

