stages:
  - deploy

deploy-job:
  stage: deploy
  image: alpine/k8s:1.24.12
  rules:
    - changes:
      - kubernetes/**/*
  script:
    - mkdir ~/.kube/
    - echo $KUBE_CONFIG > config.yaml
    - mv config.yaml ~/.kube/
    - cat /root/.kube/config.yaml
    - cd ~/.kube
    - ls -a
    - pwd
    - kubectl get pods --kubeconfig=/root/.kube/config.yaml
    

