include:
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'

stages:
  - deploy

deploy-job:
  stage: deploy
  image: alpine/k8s:1.24.12
  rules:
    - changes:
      - kubernetes/**/*
  script:
    - mkdir ~/.kube/
    - echo $KUBE_CONFIG > config
    - mv config ~/.kube/
    - cat /root/.kube/config
    - cd ~/.kube
    - ls -a
    - pwd
    - kubectl get pods --kubeconfig=/root/.kube/config
    

