stages:
  - deploy

deploy-job:
  stage: deploy
  image: alpine/k8s:1.24.12
  rules:
    - changes:
      - kubernetes/**/*
  script:
    - mkdir ~/.kube/
    - echo "$KUBE_CONFIG" > ~/.kube/config
    - cat /root/.kube/config
    - kubectl get pods 
    

