stages:
  - deploy

deploy-job:
  stage: deploy
  image: alpine/k8s:1.24.12
  rules:
    - changes:
      - kubernetes/**/*
  script:
    - mkdir ~/.kube/
    - echo $KUBE_CONFIG > config.yaml
    - mv config ~/.kube/
    - cat ~/.kube/config.yaml
    - kubectl get namespaces
    

