stages:
  - build
  - release
  # - deploy

build-helm-package:
  stage: build
  image: alpine/k8s:1.24.12
  rules:
    - changes:
      - sausage-store-chart/**/*
  script: 
    - helm package sausage-store-chart/
  # artifacts:
  #   paths:
  #     - sausage-store*.tgz
  #   expire_in: 1 day

release-helm-package:
  stage: release
  rules:
    - changes:
      - sausage-store-chart/**/*
  script:
    - ls







# apply-kuber-manifests:
#   stage: deploy
#   image: alpine/k8s:1.24.12
#   rules:
#     - changes:
#       - sausage-store-chart/**/*
#   environment:
#     name: helm
#     url: https://shelgunova-valerie-10.k8s.praktikum-services.tech/
#   script:
#     - mkdir ~/.kube/
#     - echo "$KUBE_CONFIG" | base64 -d > ~/.kube/config

#     - helm repo add sausage-store https://nexus.k8s.praktikum-services.tech/repository/sausage-store-helm-valerie-shelgunova-12/ --username std-009-052 --password 1/EnFw+8 
#     - helm repo list
#     - helm repo update 
#     - pwd
#     - ls
#     - cd sausage-store-chart/
#     -

#     - rm -f ~/.kube/config
    
  
    

