global:

  environment: production 

  backend: 
    image: 
      repository: gitlab.praktikum-services.ru:5050/std-009-052/sausage-store/sausage-backend
    imagePullPolicy: Always
    replicas: 2
    env:
      VAULT_HOST: 62.84.127.198
      VAULT_PORT: 8200
      REPORT_PATH: /var/reports
    service:
      ports:
        port: 8080

  frontend:
    image: 
      repository: gitlab.praktikum-services.ru:5050/std-009-052/sausage-store/sausage-frontend
    imagePullPolicy: Always
    replicas: 1
    service:
      ports:
        port: 56348
    ingress:
      host: shelgunova-valerie-10.k8s.praktikum-services.tech

  backend_report:
    image: 
      repository: gitlab.praktikum-services.ru:5050/std-009-052/sausage-store/sausage-backend-report
    imagePullPolicy: Always
    replicas: 1
    env:
      VAULT_URL: http://62.84.127.198:8200
      REPORT_PORT: 8080
    resources:
      requests:
        memory: "512Mi"
        cpu: 0.1
      limits:
        memory: "1025Mi"
        cpu: 0.2 
    HPA:
      minReplicas: 1
      maxReplicas: 5
      averageUtilization: 75      
    service:
      ports:
        port: 8080
    
  
  


  
