apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - "{{ .Values.global.frontend.ingress.host }}"
  rules:
    - host: "{{ .Values.global.frontend.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: {{ .Values.global.frontend.service.ports.port }}
