---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  SPRING_CLOUD_VAULT_TOKEN: aHZzLkNBRVNJQm9ZQmpJRlBSdjM5eGdRbHBhdV9JSGF1ODhHVFdkZzFkMzZSLWxyNVdlTkdoNEtIR2gyY3k1Sk9WVnRkbFJQVDNFMVJXZzFjSFo2VFd0dWRuQlVkbWM=
type: Opaque

---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIlpYSmhhMmh0WlhSNmVXRnViM1k2TlZrNWNESnlSM05RUVcxSFVIST0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson 
