---
apiVersion: v1
kind: Service
metadata:
  name: backend-report
  labels:
    app: backend-report
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.global.backend_report.service.ports.port }}
      protocol: TCP
      targetPort: 8080
  selector:
    app: backend-report 

