---
# tasks file for backend

- name: Install Java package
  apt:
      name: "{{ java_apt_package }}"
      state: present
      update_cache: yes
  become: true   
     
- name: create service user
  user:
    name: "{{ backend_service_user }}"
    create_home: no
    shell: /sbin/nologin
  become: true 

- name: install Python library lxml for maven_artifact to work
  apt:
    name: "{{ lxml_package }}"
    state: present
  become: true  

- name: create directory for jar file
  file:
    path: "{{ backend_jar_dir }}"
    state: directory
  become: true

- name: download jar file 
  maven_artifact:
    username: "{{ backend_nexus_username }}"
    password: "{{ backend_nexus_pass }}"
    dest: "{{ backend_jar_dir }}{{ backend_jar_name }}"
    repository_url: "{{ backend_nexus_repository_url }}"
    group_id: "{{ backend_nexus_group_id }}"
    artifact_id: "{{ backend_nexus_artifact_id }}"
    version: "{{ backend_jar_version }}"
    owner: "{{ backend_service_user }}"
  become: true

- name: create environment file
  template:
    src: backend_environment.j2
    dest: "{{ backend_environment_file_path }}" 
  become: true

# - name: permissions for -create report path, если она уже есть

- name: create log path
  file:
    path: "{{ backend_log_path }}"
    state: directory
  become: true


- name: create backend service file 
  template:
    src: sausage-store-backend.service.j2
    dest: "/etc/systemd/system/{{ backend_service_filename }}"
  become: true

- name: reload systemd
  systemd:
    daemon_reload: yes
  become: true

- name: start systemd
  service:
    name: sausage-store-backend.service
    state: started 
  become: true