apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    environment: {{ .Values.global.environment }}
    app: backend
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: sausage-store
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.global.backend.replicas }}
  revisionHistoryLimit: 15
  strategy:
    # 2 pod max because of "too many active clients for user" postgress error
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.global.backend.image.repository }}:{{ .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.global.backend.imagePullPolicy }}
          env:
            - name: SPRING_CLOUD_VAULT_HOST
              value: {{ .Values.global.backend.env.SPRING_CLOUD_VAULT_HOST }}
            - name: REPORT_PATH
              value: {{ .Values.global.backend.env.REPORT_PATH }}
            - name: SPRING_CLOUD_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: SPRING_CLOUD_VAULT_TOKEN
          ports:
            - name: backend
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 1
            failureThreshold: 6
      imagePullSecrets:
        - name: docker-config-secret
